[package]
name = "messages"
version = "0.1.2"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"
repository = "https://github.com/popzxc/messages-rs"
documentation = "https://docs.rs/messages"
readme = "README.md"
license = "MIT"
keywords = ["channels", "async", "actor", "utils"]
categories = ["rust-patterns"]
description = "A midground between channels and actors."

[dependencies]
futures = "0.3.5"
thiserror = "1.0"
async-trait = "0.1"
tokio = { version = "1.6", features = ["rt"], optional = true }
async-std = { version = "1.9", optional = true }

[dev-dependencies]
tokio = { version = "1.6", features = ["full"] }
anyhow = "1.0"

[features]
default = ["runtime-tokio"] # TODO: Temporary for the development purposes!
runtime-tokio = ["tokio"]
runtime-async-std = ["async-std"]

[package.metadata.docs.rs]
features = ["runtime-tokio"]
