[package]
name = "messages"
version = "0.1.2"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"
repository = "https://github.com/popzxc/messages-rs"
documentation = "https://docs.rs/messages"
readme = "README.md"
license = "MIT"
keywords = ["channels", "async", "actor", "utils"]
categories = ["rust-patterns"]
description = "A midground between channels and actors."

[dependencies]
futures = "0.3.5"
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["full"] }
