[package]
name = "messages"
version = "0.1.0"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"

[dependencies]
futures = "0.3.5"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["rt-core"] }
