[package]
name = "messages"
version = "0.1.0"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["full"] }
